company/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('company.views',
                        url(r'^$', 'index_company', name="index_company"),
                        url(r'^license_page/$', 'license_page', name="license_page"),
                        url(r'^rules_page/$', 'rules_page', name="rules_page"),
)

support/urls.py
from django.conf.urls import patterns, include, url
from tvk_rostov import views

urlpatterns = patterns('support.views',
                       url(r'^$', 'index_page', name="support"),
                       url(r'^contacts/$', 'contacts', name="contacts"),
                       url(r'^rate/$', 'rate', name="rate"),
                       url(r'^zone/$', 'zone', name="zone"),
                       url(r'^out_of_service/$', 'out_of_service', name="out_of_service"),
                       url(r'^out_of_service_post/$', 'out_of_service_post', name="out_of_service_post"),
                       url(r'^pay/$', 'pay', name="pay"),
                       url(r'^pay/sberbank/$', 'sberbank', name="sberbank"),
                       url(r'^pay/centrinvest/$', 'centrinvest', name="centrinvest"),
                       url(r'^contract/$', 'contract', name="contract"),
                       url(r'^contract/renewal/$', 'renewal', name="renewal"),
                       url(r'^contract/suspension/$', 'suspension', name="suspension"),
                       url(r'^contract/reregistration/$', 'reregistration', name="reregistration"),
                       url(r'^contract/recalculation/$', 'recalculation', name="recalculation"),
                       url(r'^contract/termination/$', 'termination', name="termination"),
                       url(r'^contract/moving/$', 'moving', name="moving"),
                       url(r'^adhrw/$', 'adhrw', name="adhrw"),
                       url(r'^conf_tv/$', 'conf_tv', name="conf_tv"),
)

requisition/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class House(models.Model):
    number = models.CharField(_('Номер дома'), unique=True, max_length=10)

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = _('Дом')
        verbose_name_plural = _('Дома')


class Street(models.Model):
    name = models.CharField(_('Улица'), unique=True, max_length=100)
    house = models.ManyToManyField(House, verbose_name=_('Номер дома'))

    class Meta:
        verbose_name = _('Улица')
        verbose_name_plural = _('Улицы')

    def __str__(self):
        return self.name


class Requisition(models.Model):
    name = models.CharField(_('Имя клиента'), max_length=100)
    street = models.CharField(_('Улица'), max_length=100, blank=True)
    house = models.CharField(_('Номер дома'), max_length=20, blank=True)
    apartment = models.PositiveSmallIntegerField(
        verbose_name=_('Номер квартиры'),
        max_length=5,
        null=True,
        blank=True, )
    no_sh = models.BooleanField(_('Нет адреса в списке'), default=False)
    phone = models.CharField(_('Номер телефона'), max_length=17)
    date = models.DateTimeField(_('Дата'), auto_now_add=True, blank=True)
    status = models.CharField(_('Статус'), max_length=20, blank=True)

    class Meta:
        verbose_name = _('Заявка')
        verbose_name_plural = _('Заявки')

    def __str__(self):
        return _('{0}, {1}, кв. {2}').format(
            self.street,
            self.status,
            self.house,
            self.apartment)

support/views.py
from django.shortcuts import render
from company.models import Contact, Payment
from requisition.models import Street
from tariff.models import Rate
from requisition.forms import RequisitionForm
from requisition.models import Street
from django.core.mail import send_mail
from django.contrib import messages
import datetime


def index_page(request):
    arr = {}
    arr["title"] = "Абонентское обслуживание"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/index.html', arr)


def contacts(request):
    arr = {}
    arr["title"] = "Контактная информация"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/contacts.html', arr)


def rate(request):
    arr = {}
    arr["title"] = "Тарифы"
    arr["rates"] = Rate.objects.all()
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/rate.html', arr)


def zone(request):
    arr = {}
    arr["title"] = "Зона охвата"
    arr["contacts"] = Contact.objects.all()
    arr["r_streets"] = Street.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/zone.html', arr)


def out_of_service(request):
    arr = {}
    arr["title"] = "Вызов специалиста"
    arr["requisitions"] = RequisitionForm()
    arr["contacts"] = Contact.objects.all()
    arr["r_streets"] = Street.objects.all().order_by("name")
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/out_of_service.html', arr)


def out_of_service_post(request):
    if request.method == 'POST':
        form = RequisitionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваша заявка была отправлена, ожидайте звонка от оператора')
            send_mail('Вызов специалиста',
                  'Телефон: ' + request.POST['phone'] + '\n' + 'Имя: ' + request.POST['name'] + '\n' +
                  'Улица: ' + request.POST['street'] + '\n' + 'Дом: ' + request.POST['house'] + '\n' +
                  'Квартира: ' + request.POST['apartment'] + 'Статус: ' + request.POST['status'] + '\n',
                  'mail@tvk-rostov.ru', ['mail@tvk-rostov.ru'])
        return out_of_service(request)


def pay(request):
    arr = {}
    arr["title"] = "Способы оплаты"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/pay.html', arr)


def sberbank(request):
    arr = {}
    arr["title"] = "Сбербанк"
    arr["contacts"] = Contact.objects.all()
    arr["pays"] = Payment.objects.all().filter(bank_beneficiary="Юго-Западный Банк ОАО «Сбербанк России»")
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/sberbank.html', arr)


def centrinvest(request):
    arr = {}
    arr["title"] = "Центр-Инвест"
    arr["contacts"] = Contact.objects.all()
    arr["pays"] = Payment.objects.all().filter(bank_beneficiary="ОАО КБ «Центр-Инвест» в. г. Ростове -на-Дону")
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/centrinvest.html', arr)


def contract(request):
    arr = {}
    arr["title"] = "Действия с договором"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/contract.html', arr)


def renewal(request):
    arr = {}
    arr["title"] = "Возобновление договора"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/renewal.html', arr)


def suspension(request):
    arr = {}
    arr["title"] = "Приостановление договора"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/suspension.html', arr)


def reregistration(request):
    arr = {}
    arr["title"] = "Переоформление договора"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/reregistration.html', arr)


def recalculation(request):
    arr = {}
    arr["title"] = "Переоформление договора"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/recalculation.html', arr)


def moving(request):
    arr = {}
    arr["title"] = "Переезд на другой адрес"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/moving.html', arr)


def termination(request):
    arr = {}
    arr["title"] = "Расторжение договора"
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    return render(request, 'support/termination.html', arr)


def adhrw(request):
    arr = {}
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    arr["title"] = "Настрйока приставки"
    return render(request, 'support/adhrw.html', arr)


def conf_tv(request):
    arr = {}
    arr["contacts"] = Contact.objects.all()
    arr["time"] = datetime.datetime.now()
    arr["title"] = "Настрйока ТВ"
    return render(request, 'support/conf_tv.html', arr)

templates/support/adhrw.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="contacts">
    <div class="center_title">
        <span>Настройка приставки</span>
    </div>
    <div class="step_1">
        <div class="fa_1">
            <iframe src="/media/docs/adhrw.pdf" width="100%" height="800px" alt="Попробуйте в другом браузере"></iframe>
        </div>
    </div>
</div>
{% endblock %}

templates/support/centrinvest.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="sberbank">
    <div class="center_title">
        <span>Оплата</span>
    </div>
    <div class="step_1">
        {% for contact in contacts %}
        <div class="fa_1">
            <p><b>Как оплатить в "Центр-Инвест"?</b></p>
            <p>Оплату за кабельное телевидение можно производить в любом отделении банка "Центр-Инвест".</p>
            <p><a href="{{ MEDIA_URL }}/docs/receipt_centrinvest.doc">Здесь</a> можно взять образец квитанции.</p>
        {% for pay in pays %}
            <table class="t_pay">
                <tr>
                    <td>Получатель</td>
                    <td>{{ pay.receiver }}</td>
                </tr>
                <tr>
                    <td>ИНН</td>
                    <td>{{ pay.vat_id }}</td>
                </tr>
                <tr>
                    <td>Расч. счёт</td>
                    <td>{{ pay.account_settlement }}</td>
                </tr>
                <tr>
                    <td>в Банке</td>
                    <td>{{ pay.bank_beneficiary }}</td>
                </tr>
                <tr>
                    <td>БИК</td>
                    <td>{{ pay.bic }}</td>
                </tr>
                <tr>
                    <td>Корр. счёт</td>
                    <td>{{ pay.account_correspondent }}</td>
                </tr>
            </table>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

templates/support/contacts.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="contacts">
    <div class="center_title">
        <span>Контактная информация</span>
    </div>
    <div class="step_1">
        {% for contact in contacts %}
        <div class="fa_1">
            <div class="f_inf">
                <span>{{ contact.phone }}</span>
                <span><a class="link" href="mailto:{{ contact.email }}" >{{ contact.email }}</a></span>
             </div>
            <div class="over_map">
                <span class="adres">Наш адрес: г. Ростов-на-Дону {{ contact.address }}</span>
                <div id="map"></div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/contract.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="contract">
    <div class="center_title">
        <span>Действия с договором</span>
    </div>
    <div class="step_1">.
        {% for contact in contacts %}
        <div class="fa_1">
            <ul>
                <li>
                    <a href="{% url 'reregistration' %}">Переоформление</a>
                </li>
                <li>
                    <a href="{% url 'suspension' %}">Приостановление</a>
                </li>
                <li>
                    <a href="{% url 'termination' %}">Расторжение</a>
                </li>
                <li>
                    <a href="{% url 'moving' %}">Переезд по другому адресу</a>
                </li>
            </ul>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/index.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="ind">
    <div class="step_1">
        <div class="center_title">
            <span>Абонентское обслуживание</span>
        </div>
        {% for contact in contacts %}
        <div class="fa_1">
            <p>Наиболее важные вопросы по разным категориям</p>
            <p>Если Вы не нашли ответ на свой вопрос, позвоните нам <b>{{ contact.phone }}</b></i></p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/menu.html
<div id="over_menu">
    <ul id="cont_menu">
        <li>
            <a class="m" href="{% url 'main_index' %}"><span>Главная страница</span></a>
        </li>
        <li class="m">
            <a href="{% url 'contacts' %}"><span>Контактная информация</span></a>
        </li>
        <li>
            <a class="m" href="{% url 'rate' %}"><span>Тарифы</span></a>
        </li>
        <li>
            <a class="m" href="{% url 'zone' %}"><span>Зона охвата</span></a>
        </li>
        <li>
            <a class="m" href="{% url 'out_of_service' %}"><span>Вызов специалиста</span></a>
        </li>
        <li>
            <a class="m" href="{% url 'pay' %}"><span>Способы оплаты</span></a>
             <ul class="submenu">
                <li>
                    <a href="{% url 'sberbank' %}">Сбербанк</a>
                </li>
                <li>
                    <a href="{% url 'centrinvest' %}">Центр-Инвест</a>
                </li>
            </ul>
        </li>
        <li>
            <a class="m" href="{% url 'contract' %}"><span>Действия с договором</span></a>
            <ul class="submenu">
                <li>
                    <a href="{% url 'reregistration' %}">Переоформление</a>
                </li>
                <li>
                    <a href="{% url 'suspension' %}">Приостановление</a>
                </li>
                <li>
                    <a href="{% url 'termination' %}">Расторжение</a>
                </li>
                <li>
                    <a href="{% url 'moving' %}">Переезд по другому адресу</a>
                </li>
            </ul>
        </li>
        <li>
            <a class="m" href="{% url 'adhrw' %}"><span>Настройка приставки</span></a>
        </li>
        <li>
            <a class="m" href="{% url 'conf_tv' %}"><span>Настройка ТВ</span></a>
        </li>
        <li class="m">
            <a href="http://tv.mail.ru/?channel=1,1352,1590,1250,4,1589,1591,336,414,409,255,330,874,227,214,226,284,552,216,623,655,650,630,369,530,407,620,432,682,677,1014,1017,1030,1035,1061,1071,1080,1216,503,109,1045,1170,560,1037,241,1592,400,204,1044,276,107,108,1657,555" target="_blank"><span>Программа телепередач</span></a>
        </li>
    </ul>
    <div id="fl"></div>
</div>

templates/support/moving.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="moving">
    <div class="center_title">
        <span>Переезд по другому адресу</span>
    </div>
    <div class="step_1">
        {% for contact in contacts %}
        <div class="fa_1">
            <p><b>Что делать при смене места жительства?</b></p>
            <p>При смене места жительства необходимо в офисе компании по адресу {{ contact.address }} имея при себе паспорт, написать заявление о расторжении договора по прежнему адресу,
            погасить существующую задолженность по договору и, при наличии технической возможности
            предоставления услуги по новому адресу, заключить новый договор.</p>
            <p>Обращаем Ваше внимание, что при одностороннем отказе от услуг компании по любым
            причинам, Вам обязательно необходимо расторгнуть договор, так как в противном случае у Вас
            будет происходить накопление задолженности по абонентской плате.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/out_of_service.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="out_of_service">
    <div class="center_title">
        <span>Вызов специалиста</span>
    </div>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="step_1">
        <div class="fa_1">
        <form id="form_ticket_1"  action="{% url 'out_of_service_post' %}" method="POST">
            {% csrf_token %}
            {{ requisitions.street }}
            <select id="street_sel" name="street_sel">
                <option selected disabled>Выберите улицу</option>
                {% for street in r_streets %}
                    <option value="{{street.id}}">{{street.name}}</option>
                {% endfor %}
            </select>
            {{ requisitions.house }}
            <select id="house_sel" name="house_sel">
                <option selected disabled>Выберите дом</option>
            </select>
                {{ requisitions.apartment }}
                {{ requisitions.name }} <br>
                {{ requisitions.phone }}
                <input id="id_status" maxlength="20" name="status" value="Вызов специалиста" type="hidden">
            <input class="but_subm" id="but_ticket_1" type="submit" value="Отправить"/>
        </form>
        </div>
    </div>
</div>
{% endblock %}

templates/support/pay.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="pay">
    <div class="center_title">
        <span>Способы оплаты</span>
    </div>
    <div class="step_1">
        <div class="fa_1">
            <p><b>Где можно оплатить?</b></p>
            <p>Оплату за кабельное телевидение можно производить в банках <b>"Центр-Инвест"</b>, <b>"Сбербанк"</b>.<br>
            Вы также можете произвести оплату в любом другом банке или интернет-банке. Но в
            этом случае Вам может быть начислена комиссия за услуги этого банка.</p>
            <p>Реквизиты для оплаты:</p>
            <p><b></b>ИНН 6164304778<b></b></p>
        <p class="warn"><b>Внимание</b></p>
        <ul>Осуществляя оплату за услуги КТВ, Абонент в обязательном порядке указывает следующие данные:
            <li>номер своего договора (000_/номер кв.), на который подлежит зачислению платеж;</li>
            <li>адрес подключения к услуге;</li>
            <li>свою фамилию и инициалы.</li>
        </ul>
        <p><i>В случае неуказания этих данных, Оператор не несет ответственности за правильность
            списания поступающих платежей.</i></p>
        </div>
    </div>
</div>
{% endblock %}

templates/support/rate.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="rate">
    <div class="center_title">
        <span>Тарифы</span>
    </div>
    <div class="step_1">
    <div class="fa_1">
        <span class="title">Стоимость подключения</span>
        {% for rate in rates %}
            <span class="pay">{{ rate.first }}р</span>
        {% endfor %}
        <ul>
            <li>Последующих ТВ точек еще дешевле!</li>
        </ul>
    </div>
    <div class="fa_1">
        <span class="title">Абонентская плата</span>
        {% for rate in rates %}
            <span class="pay">{{ rate.month }}р</span>
        {% endfor %}
        <ul>
            <li>Не зависит от количества подключенных у Вас ТВ</li>
        </ul>
    </div>
</div>
</div>
{% endblock %}

templates/support/recalculation.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="recalculation">
    <div class="center_title">
        <span>Пересчет абоненской платы</span>
    </div>
    <div class="step_1">
        <div class="fa_1">
            <p><b>В каких случаях возможен перерасчёт абонентской платы?</b></p>
            <p>При условии, что у вас не работает кабельное телевиденье по нашей вине,
                а заявка на вызов специалиста была оставлена оператору.</p>
        </div>
    </div>
</div>
{% endblock %}

templates/support/reregistration.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="reregistration">
    <div class="center_title">
        <span>Переоформление договора</span>
    </div>
    <div class="step_1">
        {% for contact in contacts %}
        <div class="fa_1">
            <p><b>Что необходимо для переоформления договора по инициативе абонента?</b></p>
            <p>Для переоформления договора по инициативе абонента на другого пользователя
            необходимо вместе, имея при себе паспорта, подъехать в офис компании по адресу {{ contact.address }}, и  переоформить договор.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/termination.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="termination">
    <div class="center_title">
        <span>Расторжение договора</span>
    </div>
    <div class="step_1">.
        {% for contact in contacts %}
        <div class="fa_1">
            <p><b>Как расторгнуть договор</b></p>
            <p>Для расторжения договора по инициативе абонента, необходимо в офисе компании по адресу  {{ contact.address }},
                имея при себе паспорт, написать заявление о расторжении договора и погасить существующую задолженность по договору.</p>
            <p>Обращаем Ваше внимание, что при одностороннем отказе от услуг компании по любым
                причинам, Вам необходимо обязательно расторгнуть договор, так как в противном случае у Вас
                будет происходить накопление задолженности по абонентской плате.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/support/zone.html
{% extends 'support/main.html' %}
{% block support_content %}
<div class="zone">
    <div class="center_title">
        <span>Зона охвата</span>
    </div>
    <div class="step_1">
        <div class="fa_1">
            <span class="title">Скорее всего мы уже обслуживаем Ваш дом</span>
                <select id="street_sel" name="street_sel">
                    <option selected disabled>Выберите улицу</option>
                    {% for street in r_streets %}
                        <option value="{{street.id}}">{{street.name}}</option>
                    {% endfor %}
                </select>
            <select id="house_sel" name="house_sel">
                <option selected disabled>Выберите дом</option>
            </select>
            <div class="fa_2">
                 <div id="map"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}